MainTab을 구현
good-potatos/Gamzabada-iOS pull request #40
Opened 2022-07-01 12:30 UTC by dev-wimes

## What is this PR?

## Changes:
* MainTab을 구현했습니다. 아래와 같이 Tab을 구성하는 정보가 담긴 배열을 넘기면 Tabbar를 만들어 줍니다.
<img width="534" alt="image" src="https://user-images.githubusercontent.com/83421954/176894694-6fbe3803-fa01-41f6-9323-121afe8ddc49.png">

## Screenshot:

## Test Checklist:

2022-07-01 13:12 UTC, dp221125 commented on Feature/Sources/MainTabInterface/MainTabState.swift
> +import MainTabInterface
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/10572119/176901312-2583b460-5a65-4f7b-af46-e488bd3d0909.png">
warning 확인해주세요

2022-07-01 13:13 UTC, dp221125 commented on Feature/Sources/MainTabInterface/MainTabState.swift
> +            ))
self.items = items.map { TabItem(view: $0.view, icon: $0.icon, title: $0.title) }

이렇게는 어떠신가요?

2022-07-01 13:14 UTC, dp221125 commented on Gamzabada/Root/RootView.swift
> +// }
안쓰는 주석이라면 삭제해주세요.

2022-07-01 13:18 UTC, dev-wimes commented
9f4a4ef3ceea24ae4588b7357caa529148ae89a9 반영했습니다.

2022-07-02 12:33 UTC, dp221125 requested changes
디자인 이슈 확인 되면 다시 핑 주세요

2022-08-21 15:42 UTC, dp221125 approved these changes

2022-08-22 11:23 UTC, merged